# Generated by Django 4.2.5 on 2023-09-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group_214', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Studentlar ruyxati', 'verbose_name_plural': 'Studentlar Ruyxati'},
        ),
    ]
